# version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - redis-network

  app:
    build: .
    container_name: node_with_Dockers
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: "127.0.0.1"
      REDIS_PORT: 6379
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
